### PR TITLE
fixed ttsdk.py and improoved downloader.py

### PR DESCRIPTION
**Pull request by techexplorers123**
added user agent to request header. added error handling in downloader.py

### CODE REVIEW

**Comment by a11cf0** [comment]
Oops, you forget to remove duplicated imports in the middle of ttsdk_downloader.py

**Comment by techexplorers123** [comment]
well i forgot anyway to edit pull request?

**Comment by techexplorers123** [comment]
> well i forgot anyway to edit pull request?

**Comment by techexplorers123** [comment]
> Oops, you forgot to remove duplicated imports in the middle of ttsdk_downloader.py

okay, i just edited it it says there is conflicts. i am new to github don't no how to proceed

**Pull request merged**
